### ISSUE TITLE
Add Multiprocessing functionality for faster .json loading/processing

### ISSUE THREAD

**Issue by jcherry-risklens** [RiskLens/verispy#11]
Loading and processing of the VCDB  files could be done faster using the multiprocessing library in Python (a good demo is here: https://sebastianraschka.com/Articles/2014_multiprocessing.html). Some off-the-cuff tests showed a 3x improvement on my end (from ~35 sec to ~11 sec) by using the Pool method in multiprocessing rather than just doing a regular for loop.

Note, TQDM and Multiprocessing can work in tandem, though is a touch tricky. I can't find a solid resource for it, but here's a snippet of my test code as a reference:
```
file_maps = list(tqdm.tqdm_notebook(p.imap(parse_func, files), total=len(files)))
```

**Comment by tbyers-risklens** [comment]
<img width="839" alt="Screen Shot 2021-01-11 at 4 14 16 PM" src="https://user-images.githubusercontent.com/38048381/104252913-199bd480-5428-11eb-88f3-ad22636bac0d.png">

Not sure if Python's gotten faster, if Pandas has, or something else...but I can load all files in like 6 seconds now, and the entire processing takes about 16. Doubtful taking the time to do multiprocessing is even worth it any more :)
