### ISSUE TITLE
No error handling in case of a bad schema URL

### ISSUE THREAD

**Issue by jcherry-risklens** [RiskLens/verispy#14]
/verispy/veris.py[333:336] has no error handling in case of a bad URL when getting the schema (if URL is used for schema collection).

**Comment by tbyers-risklens** [comment]
wouldn't `urllib` throw the error if the URL is bad?

**Comment by jcherry-risklens** [comment]
Aah, lemme revise my statement: There's nothing to handle a non-200 status return.

**Comment by tbyers-risklens** [comment]
![Uploading Screen Shot 2020-01-16 at 4.00.16 PM.png…]()

**Comment by tbyers-risklens** [comment]
<img width="820" alt="Screen Shot 2020-01-16 at 4 00 16 PM" src="https://user-images.githubusercontent.com/38048381/72573181-a2b21700-3879-11ea-8387-0013f0695007.png">
