### ISSUE TITLE
Needless type check in _enums_from_schema method?

### ISSUE THREAD

**Issue by jcherry-risklens** [RiskLens/verispy#15]
There seems to be a needless type check occuring in the _enums_from_schema method in the VERIS class (/verispy/veris.py[98]). Wouldn'd you want to raise an error if the schema param isn't a dictionary?

Also, doesn't conform to [PEP8](https://www.python.org/dev/peps/pep-0008/) standard: "Object type comparisons should always use isinstance() instead of comparing types directly."

**Comment by tbyers-risklens** [comment]
No, see what it returns -- at the end of the recursion, it returns the list of the enumerations, so the type check is important. 

Fair enough on the `isinstance` though.

**Comment by jcherry-risklens** [comment]
As it stands now it would return an empty list. Shouldn't it throw an error instead if a non-dict object is passed though?

**Comment by tbyers-risklens** [comment]
Fixed here: https://github.com/RiskLens/verispy/commit/fe86219856e8c71d8cb3df810c35c9ec5e4a206c. Will be available in next version/PR. Thanks.
