### ISSUE TITLE
Several methods still has some verbose when verbose is False

### ISSUE THREAD

**Issue by jcherry-risklens** [RiskLens/verispy#18]
The _rawjson_to_df method in veris.py does not completely respect verbose=False. Specific offenders are lines 70 (print statement) and 72 (TQDM). Both should be conditional on verbose.

Edit: Also noticed the same thing in _combine_enums_raw_df, row 172.

Looks like __init__ does as well, lines 38 & 40.

_combine_enums_raw_df line 171 & 172

json_to_df line 405.

**Comment by tbyers-risklens** [comment]
closing following PRs to address https://github.com/RiskLens/verispy/pull/21
