### ISSUE TITLE
Data Frame Returns with Columns but Zero Rows

### ISSUE THREAD

**Issue by bmumme** [RiskLens/verispy#2]
### Context:
I am attempting to use verispy to pull VCDB into a Data Frame for analysis. I followed the instructions / example on the readme.md page and the Data Frame that returns has all of the column names but has zero rows. 

### Idea:
It seems as though maybe the structure of new DB 1.3.3 doesn't read correctly with existing code. Any thoughts on what might be causing this? Or, any ideas on what I can do to fix this?

 Thanks for this tool, seems like it can be extremely useful.

**Comment by tbyers-risklens** [comment]
Hi! Sorry just noticed this issue now!

One of the "features," if you will, of this package is that it returns an empty data frame if it cannot find any applicable json files in the directory you specified. Can you please verify that you entered the correct directory with VERIS json files?

Perhaps I should update the package to raise an exception if there are no files in the specified directory, or at least print a warning.

**Comment by tbyers-risklens** [comment]
<img width="1196" alt="Screen Shot 2019-05-17 at 4 06 57 PM" src="https://user-images.githubusercontent.com/38048381/60747926-b6c9a300-9f3d-11e9-9a1c-86c16674e3fb.png">
 New behavior if no json files found in specified directory, rather than just failing silently.

**Comment by tbyers-risklens** [comment]
New behavior if no json files found in specified directory, rather than just failing silently.
<img width="1163" alt="Screen Shot 2019-07-05 at 3 57 52 PM" src="https://user-images.githubusercontent.com/38048381/60747939-d6f96200-9f3d-11e9-80e3-9aff20bc8715.png">

**Comment by tbyers-risklens** [comment]
Added above functionality to version 0.1.4. Thanks for reporting it was a problem for you. Download new package using pip.
