### ISSUE TITLE
Centralized verbose option?

### ISSUE THREAD

**Issue by jcherry-risklens** [RiskLens/verispy#23]
Yay, verbose works properly now! :-) Was thinking that having verbose set only on init, and have that carry through all methods, might be a good approach though? That way it only needs to be set once for those of us who want ALL VERBOSE ALL TEH TIME!, or the opposite.

Best implementation would be to have verbose be set to None in the method definition, but change to whatever the class verbose state is (defined on init) if verbose isn't passed explicitly.

**Comment by tbyers-risklens** [comment]
https://github.com/RiskLens/verispy/commit/29853598864e3750681281cbf7a8131eeabdc616
