### ISSUE TITLE
Add a TQDM Iterator to json_to_df(verbose=True)

### ISSUE THREAD

**Issue by jcherry-risklens** [RiskLens/verispy#4]
Would be nice to have a TQDM-style iterator added to the json_to_df method when verbose is set to true, would give a better indication on how much is left to go through for loading the DataFrame.

**Comment by tbyers-risklens** [comment]
<img width="1209" alt="Screen Shot 2019-07-05 at 3 50 30 PM" src="https://user-images.githubusercontent.com/38048381/60747883-56d2fc80-9f3d-11e9-8e97-318f8b161d49.png">

**Comment by tbyers-risklens** [comment]
Added above functionality to version 0.1.4. Thanks for reporting it was a problem for you. Download new package using pip.

**Comment by jcherry-risklens** [comment]
*does happy dance* Yay, thank you!
