### ISSUE TITLE
Employee Count is pre-one-hot-encoded

### ISSUE THREAD

**Issue by jcherry-risklens** [RiskLens/verispy#7]
The Employee Count columns (victim.employee_count.____) are pre-one-hot-encoded. When working with machine learning models this is useful, but it's a hassle when doing summary/exploratory analysis, plus it's a lot easier to convert a single categorical column to one-hot-encoding than to go vice versa. Could these columns be consolidated into a single categorical column?

**Comment by tbyers-risklens** [comment]
One of the goals with verispy is to produce a DataFrame that looks as similar as possible to the DF produced by the `verisr` R package, which the Verizon team uses to build the data set. Periodically they upload an updated CSV to the GitHub repo (https://github.com/vz-risk/VCDB/tree/master/data/csv), which is essentially the json files run through verisr. So, as annoying as this `victim.employee_count.__` business is, it's the way the guys who maintain the main project do it, so I'm going to keep it this way in `verispy` to maintain as much of a parallel process as possible. Thanks for the comment though!
