### ISSUE TITLE
Null value for random-sampled observations

### ISSUE THREAD

**Issue by jcherry-risklens** [RiskLens/verispy#8]
The "plus.sub_source" column contains nulls when the data was selected as a part of the random sample, as opposed to the oversample methods. This can cause a nuisance with analysis. Would be nice to have the default contain 'something' instead of null values in this column.

**Comment by tbyers-risklens** [comment]
Similar to my reasoning in your other issue, I'm going to leave current behavior as is https://github.com/RiskLens/verispy/issues/7 . Thanks tho.
