### ISSUE TITLE
Industry Name doesn't match formal NAICS industry designation 

### ISSUE THREAD

**Issue by jcherry-risklens** [RiskLens/verispy#9]
Current industry names are shorthand versions of proper NAICS industry titles. https://www.naics.com/search/

Total nit-pick, but if we're gonna be *strictly* by-the-book with the package, makes sense for the NAICS mappings to be just as in-line with the formal designations as the data output is with the Veris structure.

**Comment by tbyers-risklens** [comment]
So, the purpose behind the current functionality is to match what's done in `verisr`, which this package is modeled after.

However, if you'd like the full name, it's an easy fix, a one-line (ok, two line) solution here: https://github.com/RiskLens/verispy/blob/master/verispy/veris.py#L292. Change "shorter" to "title" and assign it do a different column name. I'll add a Jira story.

**Comment by tbyers-risklens** [comment]
https://github.com/RiskLens/verispy/pull/10

Added as column: 'victim.industry.fullname'
